package pt.nomorealex.medmanagement.ui;

public enum RefPane {
    MAINCUSTOMPANE,
    ADDUSERPANE,
    DETAILSUSERPANE,
    EDITUSERPANE,
    HISTORICUSERPANE,
    PILLSUSERSSCHEDULEPANE,
    ADDUSERALLERGIESPANE,
    ADDUSERILLNESSPANE,
    ADDUSERPILLPANE,
    ADDPILLPANE,
    DETAILSPILLPANE,
    EDITPILLPANE,
    ADDORDERPANE
}
